name: Quality Checks

on: [push, pull_request]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Stylelint
        run: npm run stylelint

      - name: Run unit tests with coverage
        run: npm run test -- --code-coverage --watch=false --browsers=ChromeHeadlessCI

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

      - name: Build the application
        run: npm run build

      - name: Check for npm vulnerabilities
        run: npm audit --audit-level=high

      # Example: Running Cypress component tests
      - name: Run Cypress component tests
        run: npm run cy:run

      # Example: Running Lighthouse performance tests
      - name: Run Lighthouse performance tests
        run: npm run performance-test

      # Add more steps for other quality gates as needed (SonarQube, API tests, E2E tests, etc.)
      - name: Display Success Message
        if: success()
        run: echo "Carl Ryle Escaño_______!!!"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
